project:
  type: website

website:
  title: "SummonerMatch"
  navbar:
    background: info
    search: true
    left:
      - ./Apartados/ProductBacklog.qmd
      - ./Apartados/GeneralDesign.qmd
      - ./Apartados/Sprints.qmd
      - ./Apartados/ToDo.qmd
      - ./Apartados/MockUp.qmd
      - ./Apartados/DB.qmd
      - ./Apartados/Tools.qmd
      - ./Apartados/Comentaries.qmd
      - about.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



